#!/usr/bin/env python3
"""Generate site/icons.js and site/logo.svg from icon-mcp's bundled Lucide set.

Run from ~/workspace/repo-doctor:  python3 scripts/gen_icons.py

Every icon on the site is rendered by Pratham's own icon-mcp
(ISC Lucide, pinned 1.50.0, bundled offline) instead of a CDN.
"""
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / ".." / "icon-mcp"))
from icon_mcp.icons import style_svg  # noqa: E402

SITE = Path(__file__).resolve().parents[1] / "site"

# Every data-lucide name used by index.html / app.js, plus token-UI icons.
ICON_NAMES = [
    "alert-circle", "alert-triangle", "arrow-left", "arrow-right",
    "at-sign", "check", "chevron-down", "clock", "download",
    "external-link", "eye", "eye-off", "file-text", "info",
    "key-round", "lock", "package-open", "panel-right", "rotate-ccw",
    "scale", "search", "shield-check", "sparkles", "star",
    "stethoscope", "trash-2", "x-circle",
]

def main():
    icons = {}
    for name in ICON_NAMES:
        try:
            icons[name] = style_svg(name, stroke_width=2.0, color="currentColor", size=24)
        except KeyError:
            print(f"WARNING: icon '{name}' not in bundle, skipped")
    js = (
        "/* Generated by scripts/gen_icons.py via icon-mcp (Lucide v1.50.0, ISC).\n"
        "   Do not edit by hand. To change the set, edit ICON_NAMES and re-run. */\n"
        f"const ICONS = {json.dumps(icons)};\n"
        "function paintIcons(root) {\n"
        "  (root || document).querySelectorAll('i[data-lucide]').forEach((el) => {\n"
        "    const svg = ICONS[el.getAttribute('data-lucide')];\n"
        "    if (!svg) return;\n"
        "    const t = document.createElement('template');\n"
        "    t.innerHTML = svg;\n"
        "    const node = t.content.firstChild;\n"
        "    const cls = el.getAttribute('class');\n"
        "    if (cls) node.setAttribute('class', cls);\n"
        "    el.replaceWith(node);\n"
        "  });\n"
        "}\n"
    )
    (SITE / "icons.js").write_text(js)
    print(f"wrote icons.js with {len(icons)} icons")

    # Logo: amber rounded square with the stethoscope mark in dark ink.
    src = Path(__file__).resolve().parents[1] / ".." / "icon-mcp" / "icon_mcp" / "icons" / "stethoscope.svg"
    root = ET.fromstring(src.read_text())
    inner = "".join(ET.tostring(child, encoding="unicode") for child in root)
    logo = (
        '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">\n'
        '  <rect width="64" height="64" rx="14" fill="#fbbf24"/>\n'
        '  <g transform="translate(10,10) scale(1.8333)" fill="none" stroke="#1a1005" '
        'stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n'
        f"    {inner}"
        "  </g>\n"
        "</svg>\n"
    )
    (SITE / "logo.svg").write_text(logo)
    print("wrote logo.svg")

if __name__ == "__main__":
    main()
